baseurl = "https://saiful.web.id/"
title = "Muhammad Saiful Islam"
languageCode = "id-id"
DefaultContentLanguage = "id"
theme = "hyde"
enableEmoji = true

[blackfriday]
	smartDashes = true
	latexDashes = true
	sourceRelativeLinksEval = true

[permalinks]
	post = "/:year/:month/:slug/"
	page = "/:slug/"
