baseurl = "https://saiful.web.id/"
title = "Muhammad Saiful Islam"
languageCode = "id-id"
DefaultContentLanguage = "id"
theme = "hyde"
enableRobotsTXT = true
disqusShortname = "saifulwebid"
googleAnalytics = "UA-85966390-1"
metaDataFormat = "yaml"
pluralizeListTitles = "false"

[author]
	name = "Muhammad Saiful Islam"
	email = "muhammad@saiful.web.id"

[blackfriday]
	smartDashes = true
	latexDashes = true
	sourceRelativeLinksEval = true

[permalinks]
	post = "/:year/:month/:slug/"
	page = "/:slug/"

[params]
	description = "karena hidup terakhir seseorang di muka bumi adalah tulisannya"
