baseurl = "https://saiful.web.id/"
title = "Muhammad Saiful Islam"
languageCode = "id-id"
DefaultContentLanguage = "id"
theme = "hyde"
enableRobotsTXT = true

[blackfriday]
	smartDashes = true
	latexDashes = true
	sourceRelativeLinksEval = true

[permalinks]
	post = "/:year/:month/:slug/"
	page = "/:slug/"

[params]
	disqusShortname = "saifulwebid"
	description = "karena hidup terakhir seseorang di muka bumi adalah tulisannya"
